######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 20 14:15:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Gh3c.h
SOURCES += Gh3c.cpp main.cpp
